"""M6.8 Evidence-Bound Communication Transformer - deterministic core.

The deterministic engine (M2-M5) stays authoritative for *what may be said*. This
package is the deterministic authority (the semantic envelope), the deterministic
gate (the fail-closed output validator + CTA parser), and - from M6.8-2 - the
stubbed generation lifecycle: a deterministic provider stub, an append-only
hash-chained audit store, a deterministic candidate ranker, raw-response
retention machinery, and an immutable human-review domain.

From M6.8-3: a real ``comm.anthropic_provider_adapter@1``, the allow-listed
provider-facing envelope projection, and the deterministic
``comm.provider_certification@1`` run. The adapter can reach the network when a
harness calls it, but nothing here delivers, sends, or resolves a contact.
"""

from opintel_communication.anthropic_adapter import (
    ANTHROPIC_ADAPTER_VERSION,
    ANTHROPIC_API_ENDPOINT,
    AnthropicProviderAdapter,
    GenerationConfig,
    ProviderError,
    ProviderModelIdentityError,
    ProviderRefused,
    ProviderUnavailable,
)
from opintel_communication.builder_brief import (
    BUILDER_BRIEF_VERSION,
    BuilderBrief,
    BuilderBriefAuthorityError,
    DemoMode,
    compile_builder_brief,
    render_builder_brief_markdown,
)
from opintel_communication.builder_experience import (
    BUILDER_EXPERIENCE_VERSION,
    BuilderExperience,
    BuilderExperienceAuthorityError,
    FictionalPlaceholder,
    compile_builder_experience,
    render_builder_experience_markdown,
)
from opintel_communication.builder_story import (
    BUILDER_STORY_VERSION,
    M4_PRESENTATION_FROZEN,
    BuilderStory,
    BuilderStoryAuthorityError,
    CustomerOutcomeGroup,
    ExampleScenario,
    ResultStoryStage,
    StoryInputField,
    compile_builder_story,
    render_builder_story_markdown,
)
from opintel_communication.certification import (
    ATTEMPT3_CALL_BOUNDS,
    ATTEMPT4_CALL_BOUNDS,
    ATTEMPT5_CALL_BOUNDS,
    ATTEMPT6_CALL_BOUNDS,
    ATTEMPT7_CALL_BOUNDS,
    CONFIRMED_SONNET5_PRICE_TABLE,
    DEFAULT_CALL_BOUNDS,
    HAIKU_4_5_PRICE_TABLE,
    HAIKU_CERT_BOUNDS,
    HAIKU_QUALIFICATION_BOUNDS,
    PROVIDER_CERTIFICATION_VERSION,
    SAFETY_CRITICAL_FINDING_CODES,
    SONNET_RETURN_CERT_BOUNDS,
    SONNET_RETURN_SANITY_BOUNDS,
    CertificationCallBounds,
    CertificationKey,
    CertificationReport,
    CertificationRunner,
    CertificationSafetyOutcome,
    CommunicationQuality,
    CorpusManifest,
    DriftClass,
    PriceTable,
    SyntheticEnvelopeSpec,
)
from opintel_communication.cta_parser import ParsedCta, cta_semantic_consistency, parse_cta
from opintel_communication.domain import (
    CANDIDATE_RANKER_VERSION,
    CLAIM_MANIFEST_SCHEMA_VERSION,
    CTA_PARSER_V2_VERSION,
    CTA_PARSER_V3_VERSION,
    CTA_PARSER_VERSION,
    GENERATION_ORCHESTRATOR_VERSION,
    GENERATION_STORE_VERSION,
    HUMAN_REVIEW_SCHEMA_VERSION,
    OUTPUT_VALIDATOR_V2_VERSION,
    OUTPUT_VALIDATOR_VERSION,
    RETENTION_PROPOSAL,
    SEMANTIC_ENVELOPE_SCHEMA_VERSION,
    STUB_PROVIDER_ADAPTER_VERSION,
    CandidateAuditRow,
    ClaimEvidenceLink,
    ClaimManifest,
    ClaimManifestEntry,
    ClaimType,
    CommunicationOutcome,
    FactStrength,
    GeneratedArtifact,
    GenerationCandidate,
    GenerationRecord,
    GenerationResult,
    GenerationStatus,
    HumanReview,
    HumanReviewAction,
    HumanReviewEvent,
    HumanReviewState,
    NormalizedCandidate,
    ProviderDriftDescriptor,
    RankComponent,
    RankedCandidate,
    RankScore,
    RawResponseRetention,
    SemanticEnvelope,
    ValidationResult,
    ValidatorFinding,
)
from opintel_communication.envelope import (
    assemble_envelope,
    compute_envelope_sha256,
    strength_for_fact,
)
from opintel_communication.envelope_projection import (
    PROVIDER_PROJECTION_VERSION,
    WITHHELD_FROM_PROVIDER,
    projection_sha256,
    provider_facing_projection,
)
from opintel_communication.hashing import canonical_json, chain_hash, sha256_hex, sha256_text
from opintel_communication.normalize import normalize_candidate
from opintel_communication.orchestration import GenerationOrchestrator
from opintel_communication.prompt import (
    PROMPT_TEMPLATE_ID_CERT,
    PROMPT_TEMPLATE_ID_CERT_N1,
    PROMPT_TEMPLATE_ID_CERT_V5,
    PROMPT_TEMPLATE_ID_CERT_V6,
    PROMPT_TEMPLATE_ID_CERT_V7,
    PROMPT_TEMPLATE_ID_CERT_V8,
    PROMPT_TEMPLATE_ID_CERT_V9,
    PROMPT_TEMPLATE_ID_CERT_V10,
    build_certification_prompt_bundle,
    build_certification_prompt_bundle_n1,
    build_certification_prompt_bundle_v5,
    build_certification_prompt_bundle_v6,
    build_certification_prompt_bundle_v7,
    build_certification_prompt_bundle_v8,
    build_certification_prompt_bundle_v9,
    build_certification_prompt_bundle_v10,
    build_prompt_bundle,
)
from opintel_communication.ranker import CandidateRanker
from opintel_communication.retention import (
    RawResponseVault,
    compute_expiry,
    is_expired,
    new_retention,
)
from opintel_communication.review import (
    ReviewTransitionError,
    accept_not_distinctive,
    open_review,
    reject_all,
    reject_candidate,
    select_candidate,
)
from opintel_communication.store import InMemoryGenerationStore, compute_record_hash
from opintel_communication.stub_provider import (
    StubProfile,
    StubProviderAdapter,
    parse_provider_response,
    serialize_candidates,
)
from opintel_communication.validator import OutputValidator

__all__ = [
    "ANTHROPIC_ADAPTER_VERSION",
    "ANTHROPIC_API_ENDPOINT",
    "ATTEMPT3_CALL_BOUNDS",
    "ATTEMPT4_CALL_BOUNDS",
    "ATTEMPT5_CALL_BOUNDS",
    "ATTEMPT6_CALL_BOUNDS",
    "ATTEMPT7_CALL_BOUNDS",
    "BUILDER_BRIEF_VERSION",
    "BUILDER_EXPERIENCE_VERSION",
    "BUILDER_STORY_VERSION",
    "CANDIDATE_RANKER_VERSION",
    "CLAIM_MANIFEST_SCHEMA_VERSION",
    "CONFIRMED_SONNET5_PRICE_TABLE",
    "CTA_PARSER_V2_VERSION",
    "CTA_PARSER_V3_VERSION",
    "CTA_PARSER_VERSION",
    "DEFAULT_CALL_BOUNDS",
    "GENERATION_ORCHESTRATOR_VERSION",
    "GENERATION_STORE_VERSION",
    "HAIKU_4_5_PRICE_TABLE",
    "HAIKU_CERT_BOUNDS",
    "HAIKU_QUALIFICATION_BOUNDS",
    "HUMAN_REVIEW_SCHEMA_VERSION",
    "M4_PRESENTATION_FROZEN",
    "OUTPUT_VALIDATOR_V2_VERSION",
    "OUTPUT_VALIDATOR_VERSION",
    "PROMPT_TEMPLATE_ID_CERT",
    "PROMPT_TEMPLATE_ID_CERT_N1",
    "PROMPT_TEMPLATE_ID_CERT_V5",
    "PROMPT_TEMPLATE_ID_CERT_V6",
    "PROMPT_TEMPLATE_ID_CERT_V7",
    "PROMPT_TEMPLATE_ID_CERT_V8",
    "PROMPT_TEMPLATE_ID_CERT_V9",
    "PROMPT_TEMPLATE_ID_CERT_V10",
    "PROVIDER_CERTIFICATION_VERSION",
    "PROVIDER_PROJECTION_VERSION",
    "RETENTION_PROPOSAL",
    "SAFETY_CRITICAL_FINDING_CODES",
    "SEMANTIC_ENVELOPE_SCHEMA_VERSION",
    "SONNET_RETURN_CERT_BOUNDS",
    "SONNET_RETURN_SANITY_BOUNDS",
    "STUB_PROVIDER_ADAPTER_VERSION",
    "WITHHELD_FROM_PROVIDER",
    "AnthropicProviderAdapter",
    "BuilderBrief",
    "BuilderBriefAuthorityError",
    "BuilderExperience",
    "BuilderExperienceAuthorityError",
    "BuilderStory",
    "BuilderStoryAuthorityError",
    "CandidateAuditRow",
    "CandidateRanker",
    "CertificationCallBounds",
    "CertificationKey",
    "CertificationReport",
    "CertificationRunner",
    "CertificationSafetyOutcome",
    "ClaimEvidenceLink",
    "ClaimManifest",
    "ClaimManifestEntry",
    "ClaimType",
    "CommunicationOutcome",
    "CommunicationQuality",
    "CorpusManifest",
    "CustomerOutcomeGroup",
    "DemoMode",
    "DriftClass",
    "ExampleScenario",
    "FactStrength",
    "FictionalPlaceholder",
    "GeneratedArtifact",
    "GenerationCandidate",
    "GenerationConfig",
    "GenerationOrchestrator",
    "GenerationRecord",
    "GenerationResult",
    "GenerationStatus",
    "HumanReview",
    "HumanReviewAction",
    "HumanReviewEvent",
    "HumanReviewState",
    "InMemoryGenerationStore",
    "NormalizedCandidate",
    "OutputValidator",
    "ParsedCta",
    "PriceTable",
    "ProviderDriftDescriptor",
    "ProviderError",
    "ProviderModelIdentityError",
    "ProviderRefused",
    "ProviderUnavailable",
    "RankComponent",
    "RankScore",
    "RankedCandidate",
    "RawResponseRetention",
    "RawResponseVault",
    "ResultStoryStage",
    "ReviewTransitionError",
    "SemanticEnvelope",
    "StoryInputField",
    "StubProfile",
    "StubProviderAdapter",
    "SyntheticEnvelopeSpec",
    "ValidationResult",
    "ValidatorFinding",
    "accept_not_distinctive",
    "assemble_envelope",
    "build_certification_prompt_bundle",
    "build_certification_prompt_bundle_n1",
    "build_certification_prompt_bundle_v5",
    "build_certification_prompt_bundle_v6",
    "build_certification_prompt_bundle_v7",
    "build_certification_prompt_bundle_v8",
    "build_certification_prompt_bundle_v9",
    "build_certification_prompt_bundle_v10",
    "build_prompt_bundle",
    "canonical_json",
    "chain_hash",
    "compile_builder_brief",
    "compile_builder_experience",
    "compile_builder_story",
    "compute_envelope_sha256",
    "compute_expiry",
    "compute_record_hash",
    "cta_semantic_consistency",
    "is_expired",
    "new_retention",
    "normalize_candidate",
    "open_review",
    "parse_cta",
    "parse_provider_response",
    "projection_sha256",
    "provider_facing_projection",
    "reject_all",
    "reject_candidate",
    "render_builder_brief_markdown",
    "render_builder_experience_markdown",
    "render_builder_story_markdown",
    "select_candidate",
    "serialize_candidates",
    "sha256_hex",
    "sha256_text",
    "strength_for_fact",
]
