"""M4 application and runtime ports."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID

from opintel_demo.domain import (
    DemoBundle,
    DemoCanonicalInputs,
    DemoOperation,
    DemoReviewDecision,
    DemoRevision,
    DemoRevocation,
    RuntimeSession,
    SessionIssuance,
    TelemetryEvent,
)


class DemoSourceCatalog(Protocol):
    def get_inputs(
        self, workspace_id: UUID, audit_revision_id: UUID
    ) -> DemoCanonicalInputs | None: ...


class DemoRepository(Protocol):
    def initialize(self) -> None: ...
    def create_or_get_operation(self, operation: DemoOperation) -> tuple[DemoOperation, bool]: ...
    def get_operation(self, workspace_id: UUID, operation_id: UUID) -> DemoOperation | None: ...
    def claim_operation(self, now: datetime, lease: timedelta) -> DemoOperation | None: ...
    def claim_exact_operation(
        self, operation_id: UUID, expected_created_by: str, now: datetime, lease: timedelta
    ) -> DemoOperation | None: ...
    def retry_operation(self, operation: DemoOperation, error_code: str, now: datetime) -> None: ...
    def fail_operation(self, operation: DemoOperation, error_code: str, now: datetime) -> None: ...
    def save_revision(self, operation: DemoOperation, revision: DemoRevision) -> None: ...
    def get_revision(self, workspace_id: UUID, revision_id: UUID) -> DemoBundle | None: ...
    def list_revisions(self, workspace_id: UUID, demo_id: UUID) -> tuple[DemoBundle, ...]: ...
    def save_review(self, bundle: DemoBundle, decision: DemoReviewDecision) -> DemoBundle: ...
    def save_revocation(self, bundle: DemoBundle, revocation: DemoRevocation) -> DemoBundle: ...
    def create_issuance(self, issuance: SessionIssuance) -> None: ...
    def get_issuance_by_capability_hash(self, capability_hash: str) -> SessionIssuance | None: ...
    def consume_issuance(
        self, issuance: SessionIssuance, session: RuntimeSession, now: datetime
    ) -> None: ...
    def get_session_by_token_hash(self, token_hash: str) -> RuntimeSession | None: ...
    def get_session(self, workspace_id: UUID, session_id: UUID) -> RuntimeSession | None: ...
    def save_session(self, session: RuntimeSession) -> None: ...
    def revoke_session(self, session_id: UUID, actor: str, now: datetime) -> None: ...
    def save_telemetry(self, event: TelemetryEvent) -> None: ...
    def list_telemetry(
        self, workspace_id: UUID, revision_id: UUID
    ) -> tuple[TelemetryEvent, ...]: ...


class CapabilityFactory(Protocol):
    def issue(self) -> str: ...
    def digest(self, value: str) -> str: ...
